=== pvblicltd/ang_start/mock/raml/json-schemas/create-case.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "",
  "type": "object",
  "properties": {
    "urn": {
      "id": "/urn",
      "type": "string"
    },
    "id": {
      "id": "/id",
      "type": "string"
    },
    "policeOfficerInCase": {
      "id": "/policeOfficerInCase",
      "type": "object",
      "properties": {
        "personId": {
          "id": "/policeOfficerInCase/personId",
          "type": "string"
        },
        "rank": {
          "id": "/policeOfficerInCase/rank",
          "type": "string"
        },
        "narrative": {
          "id": "/policeOfficerInCase/narrative",
          "type": "string"
        },
        "badgeNumber": {
          "id": "/policeOfficerInCase/badgeNumber",
          "type": "integer"
        }
      }
    },
    "policeSupervisor": {
      "id": "/policeSupervisor",
      "type": "object",
      "properties": {
        "personId": {
          "id": "/policeSupervisor/personId",
          "type": "string"
        },
        "rank": {
          "id": "/policeSupervisor/rank",
          "type": "string"
        },
        "narrative": {
          "id": "/policeSupervisor/narrative",
          "type": "string"
        },
        "badgeNumber": {
          "id": "/policeSupervisor/badgeNumber",
          "type": "integer"
        }
      }
    }
  },
  "required": [
    "urn",
    "id",
    "policeOfficerInCase",
    "policeSupervisor"
  ]
}

=== pvblicltd/ang_start/mock/raml/json-examples/create-case.json
{
  "urn": "22C22222222",
  "id": "7e2f843e-d639-40b3-8611-8015f3a18958",
  "policeOfficerInCase": {
            "personId": "aa746921-d839-4867-bcf9-b41db8ebc852",
            "rank": "constable",
            "narrative":"",
            "badgeNumber": 223
  },
  "policeSupervisor": {
            "personId": "ab746921-d839-4867-bcf9-b41db8ebc852",
            "rank": "sergeant",
            "narrative":"",
            "badgeNumber": 223
  }
}
