=== pvblicltd/ang_start/mock/raml/json-schemas/directions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "",
  "type": "object",
  "properties": {
    "urn": {
      "id": "/urn",
      "type": "string"
    },
    "aggregateCaseId": {
      "id": "/aggregateCaseId",
      "type": "string"
    },
    "version": {
      "id": "/version",
      "type": "integer"
    },
    "eventId": {
      "id": "/eventId",
      "type": "string"
    },
    "directions": {
      "id": "/directions",
      "type": "array",
      "items": [
        {
          "id": "/directions/0",
          "type": "object",
          "properties": {
            "title": {
              "id": "/directions/0/title",
              "type": "string"
            },
            "statutoryReference": {
              "id": "/directions/0/statutoryReference",
              "type": "string"
            },
            "instructions": {
              "id": "/directions/0/instructions",
              "type": "array",
              "items": [
                {
                  "id": "/directions/0/instructions/0",
                  "type": "object",
                  "properties": {
                    "id": {
                      "id": "/directions/0/instructions/0/id",
                      "type": "string"
                    },
                    "description": {
                      "id": "/directions/0/instructions/0/description",
                      "type": "string"
                    },
                    "timeLimit": {
                      "id": "/directions/0/instructions/0/timeLimit",
                      "type": "string"
                    },
                    "timeLimitNote": {
                      "id": "/directions/0/instructions/0/timeLimitNote",
                      "type": "string"
                    },
                    "assignee": {
                      "id": "/directions/0/instructions/0/assignee",
                      "type": "string"
                    }
                  }
                },
                {
                  "id": "/directions/0/instructions/1",
                  "type": "object",
                  "properties": {
                    "id": {
                      "id": "/directions/0/instructions/1/id",
                      "type": "string"
                    },
                    "description": {
                      "id": "/directions/0/instructions/1/description",
                      "type": "string"
                    },
                    "timeLimit": {
                      "id": "/directions/0/instructions/1/timeLimit",
                      "type": "string"
                    },
                    "timeLimitNote": {
                      "id": "/directions/0/instructions/1/timeLimitNote",
                      "type": "string"
                    },
                    "assignee": {
                      "id": "/directions/0/instructions/1/assignee",
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "id": "/directions/1",
          "type": "object",
          "properties": {
            "title": {
              "id": "/directions/1/title",
              "type": "string"
            },
            "statutoryReference": {
              "id": "/directions/1/statutoryReference",
              "type": "string"
            },
            "instructions": {
              "id": "/directions/1/instructions",
              "type": "array",
              "items": {
                "id": "/directions/1/instructions/0",
                "type": "object",
                "properties": {
                  "id": {
                    "id": "/directions/1/instructions/0/id",
                    "type": "string"
                  },
                  "description": {
                    "id": "/directions/1/instructions/0/description",
                    "type": "string"
                  },
                  "subInstructions": {
                    "id": "/directions/1/instructions/0/subInstructions",
                    "type": "array",
                    "items": [
                      {
                        "id": "/directions/1/instructions/0/subInstructions/0",
                        "type": "object",
                        "properties": {
                          "id": {
                            "id": "/directions/1/instructions/0/subInstructions/0/id",
                            "type": "string"
                          },
                          "description": {
                            "id": "/directions/1/instructions/0/subInstructions/0/description",
                            "type": "string"
                          },
                          "timeLimit": {
                            "id": "/directions/1/instructions/0/subInstructions/0/timeLimit",
                            "type": "string"
                          },
                          "timeLimitNote": {
                            "id": "/directions/1/instructions/0/subInstructions/0/timeLimitNote",
                            "type": "string"
                          },
                          "assignee": {
                            "id": "/directions/1/instructions/0/subInstructions/0/assignee",
                            "type": "string"
                          }
                        }
                      },
                      {
                        "id": "/directions/1/instructions/0/subInstructions/1",
                        "type": "object",
                        "properties": {
                          "id": {
                            "id": "/directions/1/instructions/0/subInstructions/1/id",
                            "type": "string"
                          },
                          "description": {
                            "id": "/directions/1/instructions/0/subInstructions/1/description",
                            "type": "string"
                          },
                          "timeLimit": {
                            "id": "/directions/1/instructions/0/subInstructions/1/timeLimit",
                            "type": "string"
                          },
                          "timeLimitNote": {
                            "id": "/directions/1/instructions/0/subInstructions/1/timeLimitNote",
                            "type": "string"
                          },
                          "assignee": {
                            "id": "/directions/1/instructions/0/subInstructions/1/assignee",
                            "type": "string"
                          }
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        {
          "id": "/directions/2",
          "type": "object",
          "properties": {
            "title": {
              "id": "/directions/2/title",
              "type": "string"
            },
            "statutoryReference": {
              "id": "/directions/2/statutoryReference",
              "type": "string"
            },
            "instructions": {
              "id": "/directions/2/instructions",
              "type": "array",
              "items": [
                {
                  "id": "/directions/2/instructions/0",
                  "type": "object",
                  "properties": {
                    "id": {
                      "id": "/directions/2/instructions/0/id",
                      "type": "string"
                    },
                    "description": {
                      "id": "/directions/2/instructions/0/description",
                      "type": "string"
                    },
                    "timeLimit": {
                      "id": "/directions/2/instructions/0/timeLimit",
                      "type": "string"
                    },
                    "timeLimitNote": {
                      "id": "/directions/2/instructions/0/timeLimitNote",
                      "type": "string"
                    },
                    "assignee": {
                      "id": "/directions/2/instructions/0/assignee",
                      "type": "string"
                    }
                  }
                },
                {
                  "id": "/directions/2/instructions/1",
                  "type": "object",
                  "properties": {
                    "id": {
                      "id": "/directions/2/instructions/1/id",
                      "type": "string"
                    },
                    "description": {
                      "id": "/directions/2/instructions/1/description",
                      "type": "string"
                    },
                    "timeLimit": {
                      "id": "/directions/2/instructions/1/timeLimit",
                      "type": "string"
                    },
                    "timeLimitNote": {
                      "id": "/directions/2/instructions/1/timeLimitNote",
                      "type": "string"
                    },
                    "assignee": {
                      "id": "/directions/2/instructions/1/assignee",
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  },
  "required": [
    "urn",
    "aggregateCaseId",
    "version",
    "eventId",
    "directions"
  ]
}

=== pvblicltd/ang_start/mock/ramlBck/json-examples/directions.json
{
  "urn": "T21098",
  "aggregateCaseId": "19",
  "version": 12,
  "eventId": "983129",
  "directions": [
    {
      "title": "Expert evidence",
      "statutoryReference": "Criminal Procedure Rules, rr.3.3, 3.9",
      "instructions": [
        {
          "id": "DIR-123",
          "description": "respond to court within one week",
          "timeLimit": "28 days",
		      "timeLimitNote": "Not prescribed by rules or other legislation",
          "assignee": "Defence"
        },
        {
          "id": "DIR-123",
          "description": "respond to court within one week",
		      "timeLimit": "-",
		      "timeLimitNote": "",
          "assignee": "Defence"
        }
      ]
    },
    {
      "title": "More Expert evidence",
      "statutoryReference": "Criminal Procedure Rules, rr.3.3, 3.9",
      "instructions": [
        {
		  "id": "DIR-122",
          "description": "If either party relies on expert evidence, the directions below apply.",
          "subInstructions": [
            {
              "id": "DIR-123",
              "description": "respond to court within one week",
		          "timeLimit": "28 days",
		          "timeLimitNote": "Not prescribed by rules or other legislation",
              "assignee": "Defence & Prosecution"
            },
            {
              "id": "DIR-123",
              "description": "respond to court within one week",
			        "timeLimit": "28 days",
		          "timeLimitNote": "Not prescribed by rules or other legislation",
              "assignee": "Defence & Prosecution"
            }
          ]
        }
      ]
    },
    {
      "title": "Expert evidence",
      "statutoryReference": "Criminal Procedure Rules, rr.3.3, 3.9",
      "instructions": [
        {
          "id": "DIR-123",
          "description": "respond to court within one week",
		      "timeLimit": "28 days",
		      "timeLimitNote": "Not prescribed by rules or other legislation",
          "assignee": "Defence"
        },
        {
          "id": "DIR-123",
          "description": "respond to court within one week",
		      "timeLimit": "28 days",
		      "timeLimitNote": "Not prescribed by rules or other legislation",
          "assignee": "Defence"
        }
      ]
    }
  ]
}
