=== pvblicltd/ang_start/mock/raml/json-schemas/put_charges_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "urn": {
      "type": "string"
    },
    "suspects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "long"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "dateOfBirth": {
            "type": "string"
          },
          "proposedCharges": {
            "type": "array",
            "items": []
          },
          "putCharges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== pvblicltd/ang_start/mock/ramlBck/json-examples/put_charges.json
{
  "id": "064a09a9-377f-4c89-b185-94ad87ee95c2",
  "version": 0,
  "urn": "#1001",
  "suspects": [
    {
      "id": 123,
      "firstName": "OLIVER",
      "lastName": "smith",
      "address": "London",
      "dateOfBirth": "1996-10-17",
      "proposedCharges": [],
      "putCharges": [
        {
		  "putChargeDate": "2015-10-26",
          "code": "DDCode",
          "description": "Person is guilty"
        }
      ]
    }
  ]
}
