=== pvblicltd/ang_start/mock/ramlBck/json-schemas/witnesses.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "",
  "type": "array",
  "items": {
    "id": "/0",
    "type": "object",
    "properties": {
      "id": {
        "id": "/0/id",
        "type": "string"
      },
      "personId": {
        "id": "/0/personId",
        "type": "string"
      },
      "policePersonId": {
        "id": "/0/policePersonId",
        "type": "string"
      },
      "statements": {
        "id": "/0/statements",
        "type": "array",
        "items": [
          {
            "id": "/0/statements/0",
            "type": "string"
          },
          {
            "id": "/0/statements/1",
            "type": "string"
          }
        ]
      },
      "classification": {
        "id": "/0/classification",
        "type": "object",
        "properties": {
          "isVictim": {
            "id": "/0/classification/isVictim",
            "type": "boolean"
          },
          "isEntitlementRequired": {
            "id": "/0/classification/isEntitlementRequired",
            "type": "boolean"
          },
          "witnessExpertise": {
            "id": "/0/classification/witnessExpertise",
            "type": "string"
          },
          "witnessStatus": {
            "id": "/0/classification/witnessStatus",
            "type": "string"
          }
        }
      }
    },
    "required": [
      "id",
      "personId",
      "policePersonId",
      "statements",
      "classification"
    ]
  },
  "required": [
    "0"
  ]
}

=== pvblicltd/ang_start/mock/raml/json-examples/witnesses.json
[
  {
      "id" : "7e2f843e-d639-40b3-8611-8015f3a18958",
      "personId": "7e2f843e-d639-40b3-8611-8015f3a18958",
      "policePersonId": "policePersonId", 
      "statements": [ "id5", "id6" ],
      "classification" : {
      			"isVictim":true,
      			"isEntitlementRequired":true,
      			"witnessExpertise":"EXPERT",
      			"witnessStatus":"INTIMIDATED"
      			}
  }
]
